Bugfix: InvalidOperationException when setting the EntityFrameworkConfiguration. The problem might be caused by setting EF configuration in two different assemblies or domains: 1. ServerDom.Orm assembly loaded from memory stream, used in EntityFrameworkGenerateMetadataFiles class, and 2. ServerDom.Orm dll loaded from Generated subfolder, used in KeepSynchronizedRecomputeOnDeploy.
The exception message:
InvalidOperationException: An instance of 'EntityFrameworkConfiguration' cannot be set because an instance of 'EntityFrameworkConfiguration' is already being used. Only one DbConfiguration type can be used in an application. See http://go.microsoft.com/fwlink/?LinkId=260883 for more information.